/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as E2eNetworkGuardRouteImport } from './routes/e2e-network-guard'
import { Route as E2eTenantDirectoryRouteImport } from './routes/e2e-tenant-directory'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eNetworkGuardRoute = E2eNetworkGuardRouteImport.update({
  id: '/e2e-network-guard',
  path: '/e2e-network-guard',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eTenantDirectoryRoute = E2eTenantDirectoryRouteImport.update({
  id: '/e2e-tenant-directory',
  path: '/e2e-tenant-directory',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/e2e-network-guard': typeof E2eNetworkGuardRoute
  '/e2e-tenant-directory': typeof E2eTenantDirectoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/e2e-network-guard': typeof E2eNetworkGuardRoute
  '/e2e-tenant-directory': typeof E2eTenantDirectoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/e2e-network-guard': typeof E2eNetworkGuardRoute
  '/e2e-tenant-directory': typeof E2eTenantDirectoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/e2e-network-guard' | '/e2e-tenant-directory'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/e2e-network-guard' | '/e2e-tenant-directory'
  id: '__root__' | '/' | '/e2e-network-guard' | '/e2e-tenant-directory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  E2eNetworkGuardRoute: typeof E2eNetworkGuardRoute
  E2eTenantDirectoryRoute: typeof E2eTenantDirectoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e-network-guard': {
      id: '/e2e-network-guard'
      path: '/e2e-network-guard'
      fullPath: '/e2e-network-guard'
      preLoaderRoute: typeof E2eNetworkGuardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e-tenant-directory': {
      id: '/e2e-tenant-directory'
      path: '/e2e-tenant-directory'
      fullPath: '/e2e-tenant-directory'
      preLoaderRoute: typeof E2eTenantDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  E2eNetworkGuardRoute: E2eNetworkGuardRoute,
  E2eTenantDirectoryRoute: E2eTenantDirectoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
