// Generated by `supabase gen types typescript` — populated in PR1
// (DB Foundation) once `supabase/migrations/*.sql` exist. Do not hand-edit
// once generated; regenerate from the schema instead.
export {};
